### ISSUE TITLE
Does not build as a module

### ISSUE THREAD

**Issue by jrick** [nomasters/handshake#9] opened 2019-04-10 14:06 UTC
The presence of go.{mod,sum} indicates it should support module builds, but the build fails with:

```
$ go build
go: finding github.com/whyrusleeping/tar-utils v0.0.0-20180509141711-8c6c8ba81d5c
go: finding github.com/cheekybits/is v0.0.0-20150225183255-68e9c0620927
go: finding github.com/fatih/color v1.7.0
go: finding github.com/btcsuite/btcd v0.0.0-20181013004428-67e573d211ac
go: finding github.com/multiformats/go-multihash v1.0.8
go: finding github.com/ipfs/go-ipld-format v0.8.0
go: finding github.com/gdamore/tcell v1.1.0
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/libp2p/go-libp2p-pubsub v0.10.2
go: finding github.com/ipfs/go-ipfs-cmdkit v1.1.3
go: github.com/ipfs/go-ipld-format@v0.8.0: unknown revision v0.8.0
go: finding github.com/smartystreets/assertions v0.0.0-20190116191733-b6c0e53d7304
go: github.com/libp2p/go-libp2p-pubsub@v0.10.2: unknown revision v0.10.2
go: github.com/multiformats/go-multihash@v1.0.8: unknown revision v1.0.8
go: finding github.com/libp2p/go-libp2p-peer v2.4.0+incompatible
go: finding github.com/multiformats/go-multiaddr-net v1.6.3
go: finding github.com/lucasb-eyer/go-colorful v0.0.0-20181028223441-12d3b2882a08
go: github.com/ipfs/go-ipfs-cmdkit@v1.1.3: unknown revision v1.1.3
go: finding github.com/ipfs/go-cid v0.9.0
go: github.com/multiformats/go-multiaddr-net@v1.6.3: unknown revision v1.6.3
go: finding github.com/spf13/viper v1.2.1
go: github.com/libp2p/go-libp2p-peer@v2.4.0+incompatible: unknown revision v2.4.0
go: finding github.com/libp2p/go-libp2p-crypto v2.0.1+incompatible
go: github.com/ipfs/go-cid@v0.9.0: unknown revision v0.9.0
go: finding github.com/libp2p/go-libp2p-metrics v2.1.7+incompatible
go: finding github.com/libp2p/go-libp2p-protocol v1.0.0
go: finding github.com/gdamore/encoding v0.0.0-20151215212835-b23993cbb635
go: github.com/libp2p/go-libp2p-metrics@v2.1.7+incompatible: unknown revision v2.1.7
go: finding github.com/ipfs/go-ipfs-api v1.3.5
go: finding github.com/nomasters/hashmap v0.0.0-20181007042452-82aea241b8e7
go: github.com/libp2p/go-libp2p-crypto@v2.0.1+incompatible: unknown revision v2.0.1
go: github.com/libp2p/go-libp2p-protocol@v1.0.0: unknown revision v1.0.0
go: finding github.com/ipfs/go-block-format v0.2.0
go: finding github.com/mattn/go-runewidth v0.0.3
go: finding github.com/ipfs/go-ipfs-util v1.2.8
go: finding github.com/rivo/tview v0.0.0-20181110120306-8cf347b745d0
go: github.com/ipfs/go-ipfs-api@v1.3.5: unknown revision v1.3.5
go: finding golang.org/x/crypto v0.0.0-20181001203147-e3636079e1a4
go: finding github.com/libp2p/go-flow-metrics v0.2.0
go: finding github.com/multiformats/go-multiaddr v1.3.0
go: github.com/ipfs/go-block-format@v0.2.0: unknown revision v0.2.0
go: finding github.com/whyrusleeping/base32 v0.0.0-20170828182744-c30ac30633cc
go: finding github.com/multiformats/go-multibase v0.3.0
go: github.com/ipfs/go-ipfs-util@v1.2.8: unknown revision v1.2.8
go: github.com/libp2p/go-flow-metrics@v0.2.0: unknown revision v0.2.0
go: github.com/multiformats/go-multibase@v0.3.0: unknown revision v0.3.0
go: github.com/multiformats/go-multiaddr@v1.3.0: unknown revision v1.3.0
go: error loading module requirements
```

This looks due to missing tags.  For example, `go-ipld-format` is required at version v0.8.0, but there is no v0.8.0 tag on that repo.

**Comment by n2p5** [comment] 2019-04-10 14:08
@jrick good catch. I'll take a look at this.

**Comment by n2p5** [comment] 2019-04-10 14:16
yep. confirmed on the docker build. Looks like I was flying too fast and loose. I'll get the deps sorted out and update you.

**Comment by n2p5** [comment] 2019-04-10 15:09
ok. A MUCH cleaner dep graph now. I removed a bunch of experiments in the `/x` dir that weren't needed and bumped `hashmap` deps as well. so we have a much cleaner mod file now.
```
module github.com/nomasters/handshake

require (
	github.com/fatih/color v1.7.0
	github.com/mattn/go-colorable v0.1.1 // indirect
	github.com/mattn/go-isatty v0.0.7 // indirect
	github.com/multiformats/go-multihash v0.0.1
	github.com/nomasters/hashmap v0.0.4
	github.com/spf13/cobra v0.0.3
	github.com/spf13/viper v1.3.2
	go.etcd.io/bbolt v1.3.2
	golang.org/x/crypto v0.0.0-20190404164418-38d8ce5564a5
	gopkg.in/yaml.v2 v2.2.2
)
```

I've also bumped the Dockerfile to go1.12.3 and it does a completely clean mod build using
`make build` in the root of the repo. 

Its confirmed working now. I've also tagged this confirmed working commit as `v0.0.1` now too.
Thanks for opening this :) Closing.

**Closed as completed by n2p5** 2019-04-10 15:09 UTC
Labels: bug
